#
# This file is part of storm-docker.
# Copyright (C) 2021 INPE.
#
# storm-docker is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#
ARG BASE_IMAGE=jupyter/minimal-notebook@sha256:f424aa7321d0dd5543ac86c3efa8ec583efd8c1771266ced1b3449487e0adb63
FROM ${BASE_IMAGE}

#
# General Metadata
#
LABEL "org.storm.title"="Python Geospatial Libraries and JupyterLab in Docker"
LABEL "org.storm.description"="Software environment to use Storm Client"

#
# Maintainer metadata
#
LABEL "org.storm.maintainer"="Felipe Menino Carlos"
LABEL "org.storm.maintainer_email"="felipe.carlos@inpe.br"
